### ISSUE TITLE
ein:tb-jump-to-source-at-point-command doesn't work with ipython-styled traceback

### ISSUE THREAD

**Issue by yarikoptic** [tkf/emacs-ipython-notebook#90]
zeroin.el-ed start of the ein.

if I go to the traceback (C-c C-x):

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-7ce87d144d3c> in <module>()
      2 from mvpa2.clfs.knn import kNN
      3 clf = kNN()
----> 4 clf.train(a)

/usr/lib/pymodules/python2.7/mvpa2/base/learner.pyc in train(self, ds)
    127         else:
    128             # in this case we claim to have no idea and simply try to train
--> 129             result = self._train(ds)
    130 
    131         # store timing

/usr/lib/pymodules/python2.7/mvpa2/clfs/knn.pyc in _train(self, data)
    116         """
    117         self.__data = data
--> 118         labels = data.sa[self.get_space()].value
    119         uniquelabels = data.sa[self.get_space()].unique
    120         Nuniquelabels = len(uniquelabels)

AttributeError: 'numpy.ndarray' object has no attribute 'sa'
```

 ENTER doesn't jump to the corresponding source location because probably hoping to see a simple "file:lineno" format, spits out a message

```
File /usr/lib/pymodules/python2.7/mvpa2/base/learner.pyc in train(self, ds)
    127         else:
    128             # in this case we claim to have no idea and simply try to train
--> 129             result = self._train(ds)
    130 
    131         # store timing

 does not exit.
```

**Comment by tkf** [comment]
Where is your cursor when you hit enter?  Probably at the line of /usr/lib/pymodules/python2.7/mvpa2/base/learner.pyc?

Also, is the traceback highlighted or is it monochrome?

**Comment by yarikoptic** [comment]
On Thu, 06 Dec 2012, Takafumi Arakaki wrote:

>    Where is your cursor when you hit enter? Probably at the line of
>    /usr/lib/pymodules/python2.7/mvpa2/base/learner.pyc?

I have tried at different locations I believe.... yeap -- regardless
where I hit ENTER -- the same msg

>    Also, is the traceback highlighted or is it monochrome?

highlighted

## 

Yaroslav O. Halchenko
Postdoctoral Fellow,   Department of Psychological and Brain Sciences
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by tkf** [comment]
Do you have the same problem after updating Emacs?

**Comment by yarikoptic** [comment]
NO! works fine in emacs 24.2.1

**Comment by tkf** [comment]
I can reproduce this in Emacs 23.3.1.  According to the system info you gave me in #88 you were using 23.4.1.  So, I guess it is the problem only visible in 23.x.
